require: rubocop-rails
Metrics/MethodLength:
  Max: 500
Metrics/BlockLength:
  Max: 500
Metrics/LineLength:
  Max: 250
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false