version: '2'
services:
  web:
    image: 'quay.io/congomines/website:latest'
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - /mnt/congomines/website/files:/app/public/system
    ports:
      - "3000:3000"
    depends_on:
      - db
   env_file:
      - .env
  db:
    image: 'postgres:9.4'
    env_file:
      - .env
    volumes:
      - /mnt/congomines/website/db-data:/var/lib/postgresql/data
      - /mnt/congomines/website/config/docker-init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"