FROM ruby:2.1 

MAINTAINER Kris Carle <kris@maphubs.com>

RUN gem install bundler

ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN cd /app && bundle install

RUN apt-get update && apt-get install -y nodejs && \
apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD Rakefile /app/Rakefile
ADD config.ru /app/config.ru

WORKDIR /app
EXPOSE 3000
CMD /app/docker-entrypoint.sh